version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: sillylittleusername
      POSTGRES_DB: omerodatabase1
      POSTGRES_PASSWORD: laviolettefamilysecret
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    build: https://github.com/barrettMCW/docker-omero-serverLLAB.git
    env_file:
      - omeroserver.env
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: "${POSTGRES_USER}"
      CONFIG_omero_db_pass: "${POSTGRES_PASSWORD}"
      CONFIG_omero_db_name: "${POSTGRES_DB}"
    networks:
      - omero
    ports:
      - "4064:4064"
      - "4066:4066"
    volumes:
      - "omero:/OMERO"
      - "./certs:/etc/ssl/selfsigned:ro${VOLOPTS-}"

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    build: https://github.com/barrettMCW/docker-omero-webLLAB.git
    environment:
      OMEROHOST: omeroserver
      CONFIG_omero_web__check_version: "false"
    networks:
      - omero
    ports:
      - "4080:4080"

  nginx:
    image: library/nginx:1.14
    networks:
      - omero
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro${VOLOPTS-}"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro${VOLOPTS-}"
      - "./certs:/etc/nginx/ssl:ro${VOLOPTS-}"

networks:
  omero:

volumes:
  database:
  omero:
