version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: sillylittleusername
      POSTGRES_PASSWORD: laviolettefamilysecret
      POSTGRES_DB: omerodatabase1
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    build: https://github.com/barrettMCW/docker-omero-serverLLAB.git
    env_file:
      - omeroserver.env
    environment:
      #password for root
      ROOTPASS: omero
      #name of postgres container
      CONFIG_omero_db_host: database
      #POSTGRES_USER
      CONFIG_omero_db_user: sillylittleusername
      #POSTGRES_PASSWORD
      CONFIG_omero_db_pass: laviolettefamilysecret
      #POSTGRES_DB
      CONFIG_omero_db_name: omerodatabase1
    networks:
      - omero
    ports:
      - "4064:4064"
      - "4066:4066"
    volumes:
      - "dataset:${DATA_PATH:-/dev/null}:/OMERO.data:ro"
      - "omero:/OMERO"
      - "./certs:/etc/ssl/selfsigned:ro${VOLOPTS-}"

  omeroweb:
    build: https://github.com/barrettMCW/docker-omero-webLLAB.git
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"
    volumes:
      - "static:/opt/omero/web/OMERO.web/var/static/"

  nginx:
    image: library/nginx:1.14
    networks:
      - omero
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "static:/opt/omero/nginx/static/:ro${VOLOPTS-}"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro${VOLOPTS-}"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro${VOLOPTS-}"
      - "./certs:/etc/nginx/ssl:ro${VOLOPTS-}"

networks:
  omero:

volumes:
  database:
  omero:
  static:
    driver_opts:
      type: tmpfs
      device: tmpfs
