version: "3"

services:

  database:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: sillylittleusername
      POSTGRES_PASSWORD: laviolettefamilysecret
      POSTGRES_DB: omerodatabase1
      POSTGRES_INITDB: /wal/
      PGDATA: /data/
    networks:
      - backend
    volumes:
      - "./DATA2/omeroZFS/postgre/data/:/data/"
      - "./DATA2/omeroZFS/postgre/wal/:/wal/"
      - "./omero-conf/omero-db.conf:/etc/postgresql/postgresql.conf:ro"
      - "./DATA2/omeroZFS/logs/postgres/:/log/"

  omeroserver:
    build: https://github.com/barrettMCW/docker-omero-serverLLAB.git
    env_file: ./omero-conf/omero-server.env
    environment:
      #password for root
      ROOTPASS: omero
      #password for importer
      IMPORTPASS: omero
      #name of importer group should you have a dataset
      IMPORTGROUP: lavioletteLab
      #name of postgres container
      CONFIG_omero_db_host: database
      #POSTGRES_USER
      CONFIG_omero_db_user: sillylittleusername
      #POSTGRES_PASSWORD
      CONFIG_omero_db_pass: laviolettefamilysecret
      #POSTGRES_DB
      CONFIG_omero_db_name: omerodatabase1
    networks:
      - backend
      - frontend
    ports:
      - "4064:4064"
      - "4066:4066"
    volumes:
      - "./DATA2/omeroZFS/server/:/OMERO/"
      - "./DATA2/omeroZFS/omeTIFF/:/database/:ro"
      - "./certs:/etc/ssl/omero:ro${VOLOPTS-}"
      - "./DATA2/omeroZFS/logs/server/:/opt/omero/server/OMERO.server/var/log/"
      - "/var/run/docker.sock:/var/run/docker.sock"

  omeroweb:
    build: https://github.com/barrettMCW/docker-omero-webLLAB.git
    env_file: ./omero-conf/omero-web.env
    environment:
      OMEROHOST: omeroserver
    networks:
      - frontend
    ports:
      - "4080"
    volumes:
      - "static:/opt/omero/web/OMERO.web/var/static/"
      - "./DATA2/omeroZFS/logs/web/:/opt/omero/web/OMERO.web/var/log/"

  nginx:
    image: owasp/modsecurity-crs:nginx-alpine
    networks:
      - frontend
    depends_on:
      - omeroserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "static:/opt/omero/nginx/static/:ro${VOLOPTS-}"
      - "./certs/:/etc/nginx/ssl:ro${VOLOPTS-}"
      - "./DATA2/omeroZFS/logs/nginx/:/var/log/nginx/"
  redis:
    image: redis:latest
    networks:
      - frontend
    ports:
      - "6379"

  pipeline:
    build: https://github.com/LavLabInfrastructure/HistoQCLLAB.git
    env_file: omero-conf/hqc.env
    volumes:
      - "./DATA2/in/BRAIN/:/in/BRAIN/"
      - "./DATA2/in/PROSTATE/:/in/PROSTATE/"
      - "./DATA2/in/OVERRIDE/:/in/OVERRIDE/"
      - "./DATA2/omeroZFS/omeTIFF/:/out/"
      - "./DATA2/omeroZFS/rawTiff/:/archive/"
      - "./DATA2/omeroZFS/failed/:/fail/"
      - "./DATA2/omeroZFS/logs/pipeline/:/log/"

networks:
  frontend:
  backend:

#static web files in temp filesys
volumes:
  static:
    driver_opts:
      type: tmpfs
      device: tmpfs
