version: "3"

services:

  test:
    build: ./test
    command:
      - -c
      - /opt/omero/server/venv3/bin/pytest -p no:cacheprovider /test/tests.py
    networks:
      - omero
    volumes:
      - "./test:/test:ro${VOLOPTS-}"
