version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: sillylittleusername
      POSTGRES_PASSWORD: laviolettefamilysecret
      POSTGRES_DB: omerodatabase1
    networks:
      - backend
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    build: https://github.com/barrettMCW/docker-omero-serverLLAB.git
    env_file:
      - omeroserver.env
    environment:
      #password for root
      ROOTPASS: omero
      #name of postgres container
      CONFIG_omero_db_host: database
      #POSTGRES_USER
      CONFIG_omero_db_user: sillylittleusername
      #POSTGRES_PASSWORD
      CONFIG_omero_db_pass: laviolettefamilysecret
      #POSTGRES_DB
      CONFIG_omero_db_name: omerodatabase1
    links:
      - "redis:cache"
    networks:
      - backend
      - frontend
    ports:
      - "4064:4064"
      - "4066:4066"
    volumes:
      #replace dev/null with path to sample pictures (and uncomment)
      #- "dev/null:/dataset:ro"
      - "omero:/OMERO"
      - "./certs:/etc/ssl/omero:ro${VOLOPTS-}"

  omeroweb:
    #build: https://github.com/barrettMCW/docker-omero-webLLAB.git
    build: ../docker-omero-webLLAB
    environment:
      OMEROHOST: omeroserver
    networks:
      - frontend
    ports:
      - "4080:4080"
    volumes:
      - "static:/opt/omero/web/OMERO.web/var/static/"

  nginx:
    image: library/nginx:1.14
    networks:
      - frontend
    depends_on:
      - omeroserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "static:/opt/omero/nginx/static/:ro${VOLOPTS-}"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro${VOLOPTS-}"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro${VOLOPTS-}"
      - "./certs:/etc/nginx/ssl:ro${VOLOPTS-}"
  redis:
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - cache:/data
networks:
  frontend:
  backend:

volumes:
  #redis cache
  cache:
  #postgresdb
  database:
  #image binaries
  omero:
  #static web files in temp filesys
  static:
    driver_opts:
      type: tmpfs
      device: tmpfs
